// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	models "github.com/oleksandr-chornovol/lets-go-chat/app/models"
	mock "github.com/stretchr/testify/mock"
)

// ActiveUsersCacheInterface is an autogenerated mock type for the ActiveUsersCacheInterface type
type ActiveUsersCacheInterface struct {
	mock.Mock
}

// AddUser provides a mock function with given fields: user
func (_m *ActiveUsersCacheInterface) AddUser(user models.User) {
	_m.Called(user)
}

// DeleteUser provides a mock function with given fields: userId
func (_m *ActiveUsersCacheInterface) DeleteUser(userId string) {
	_m.Called(userId)
}

// GetAllUsers provides a mock function with given fields:
func (_m *ActiveUsersCacheInterface) GetAllUsers() map[string]models.User {
	ret := _m.Called()

	var r0 map[string]models.User
	if rf, ok := ret.Get(0).(func() map[string]models.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]models.User)
		}
	}

	return r0
}
