// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package http

import (
	"github.com/oleksandr-chornovol/lets-go-chat/app/http/controllers"
	"github.com/oleksandr-chornovol/lets-go-chat/app/models"
	"github.com/oleksandr-chornovol/lets-go-chat/cache"
)

// Injectors from wire.go:

func NewUserController() *controllers.UserController {
	token := models.NewTokenModel()
	user := models.NewUserModel()
	userController := controllers.NewUserController(token, user)
	return userController
}

func NewChatController() *controllers.ChatController {
	activeUsersCache := cache.NewActiveUsersCache()
	message := models.NewMessageModel()
	token := models.NewTokenModel()
	user := models.NewUserModel()
	chatController := controllers.NewChatController(activeUsersCache, message, token, user)
	return chatController
}
