// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	models "github.com/oleksandr-chornovol/lets-go-chat/app/models"
	mock "github.com/stretchr/testify/mock"
)

// MessageInterface is an autogenerated mock type for the MessageInterface type
type MessageInterface struct {
	mock.Mock
}

// CreateMessage provides a mock function with given fields: message
func (_m *MessageInterface) CreateMessage(message models.Message) (models.Message, error) {
	ret := _m.Called(message)

	var r0 models.Message
	if rf, ok := ret.Get(0).(func(models.Message) models.Message); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Get(0).(models.Message)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Message) error); ok {
		r1 = rf(message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessagesFromTime provides a mock function with given fields: time
func (_m *MessageInterface) GetMessagesFromTime(time string) []models.Message {
	ret := _m.Called(time)

	var r0 []models.Message
	if rf, ok := ret.Get(0).(func(string) []models.Message); ok {
		r0 = rf(time)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Message)
		}
	}

	return r0
}
