// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	models "github.com/oleksandr-chornovol/lets-go-chat/app/models"
	mock "github.com/stretchr/testify/mock"
)

// TokenInterface is an autogenerated mock type for the TokenInterface type
type TokenInterface struct {
	mock.Mock
}

// CreateToken provides a mock function with given fields: token
func (_m *TokenInterface) CreateToken(token models.Token) (models.Token, error) {
	ret := _m.Called(token)

	var r0 models.Token
	if rf, ok := ret.Get(0).(func(models.Token) models.Token); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(models.Token)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Token) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTokenById provides a mock function with given fields: id
func (_m *TokenInterface) GetTokenById(id string) (models.Token, error) {
	ret := _m.Called(id)

	var r0 models.Token
	if rf, ok := ret.Get(0).(func(string) models.Token); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Token)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
